# prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "django_app"
    metrics_path: "/metrics"
    static_configs:
      - targets: [ "App-lb-prod-frontend-750195768.eu-west-2.elb.amazonaws.com:8080" ]


