# prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "django_app"
    metrics_path: "/metrics"
    static_configs:
      - targets: [ "Promethues-lbprod-b-1226531618.eu-west-2.elb.amazonaws.com:8000" ]


