# prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "django_app"
    metrics_path: "/metrics"
    static_configs:
      - targets: [ "Promethues-lbprod-b-1226531618.eu-west-2.elb.amazonaws.com:8000" ]


#scrape_configs:
#  - job_name: 'django_app'
#    ecs_sd_configs:
#      - region: eu-west-2
#        cluster: esc-prod-cluster
#        launch_type: FARGATE
#        port: 8000
#    relabel_configs:
#      - source_labels: [__meta_ecs_task_definition_family]
#        regex: ECS-FAMILY
#        action: keep
